### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by hwaphon** [zhixuanziben/NeteaseCloudMusic-vue#1]
我也是用 Binaryify 提供的网易云接，可是当我获取到音乐的 url 地址放到 Audio 中以后，会出现请求 403 Forbidden 错误，你是怎么解决的呢？谢谢

**Comment by zhixuanziben** [comment]
不好意思，我印象中我应该没遇到这个问题，你可以去问问Binaryify，他比较专业

**Comment by hwaphon** [comment]
谢谢，我已经解决了
